#pragma once

#define NCG(x) "(?:" x ")"

#define FMT_MESSAGE NCG("(?::" FMT_PREFIX FMT_SPACE ")?" FMT_COMMAND "(?:" FMT_PARAMS ")?" FMT_CRLF)
#define FMT_PREFIX NCG(FMT_SERVERNAME "|(?:" FMT_NICKNAME "(?:(?:\\!" FMT_USER ")?@" FMT_HOST ")?)")
#define FMT_COMMAND NCG(FMT_LETTER "+|" FMT_DIGIT "{3}")
#define FMT_PARAMS NCG("(?:(?:" FMT_SPACE FMT_MIDDLE "){0,14}(?:" FMT_SPACE ":" FMT_TRAILING ")?)|(?:(?:" FMT_SPACE FMT_MIDDLE "){14}(?:" FMT_SPACE "(?::)?" FMT_TRAILING ")?")
#define FMT_NOSPCRLFCL NCG("x01-\\x09]|[\\x0B-\\x0C]|[\\x0E-\\x1F]|[\\x21-\\x39]|[\\x3B-\\xFF")
#define FMT_MIDDLE NCG(FMT_NOSPCRLFCL "(?::|" FMT_NOSPCRLFCL ")*")
#define FMT_TRAILING NCG("(?::| |" FMT_NOSPCRLFCL ")*")
#define FMT_SPACE NCG("\\x20")
#define FMT_CRLF NCG("\\x0D\\x0A")

#define FMT_TARGET NCG(FMT_NICKNAME "|" FMT_SERVER)
#define FMT_MSGTARGET NCG(FMT_MSGTO "(?:," FMT_MSGTO ")*")
#define FMT_MSGTO NCG(NCG(FMT_CHANNEL) "|" NCG(FMT_USER "(?:%" FMT_HOST ")?@" FMT_SERVERNAME) "|" NCG(FMT_USER "%" FMT_HOST) "|" NCG(TARGETMASK) "|" NCG(FMT_NICKNAME) "|" NCG(FMT_NICKNAME "!" FMT_USER "@" FMT_HOST))
#define FMT_CHANNEL NCG(NCG("#|\\+|" NCG("!" FMT_CHANNELID) "|&") FMT_CHANSTRING "(?::" FMT_CHANSTRING ")?")
#define FMT_SERVERNAME NCG(FMT_HOSTNAME)
#define FMT_HOST NCG(FMT_HOSTNAME "|" FMT_HOSTADDR)
#define FMT_HOSTNAME NCG(FMT_SHORTNAME "(?:\\." FMT_SHORTNAME ")*")
#define FMT_SHORTNAME NCG(NCG(FMT_LETTER "|" FMT_DIGIT) "(?:" FMT_LETTER "|" FMT_DIGIT "|-)*(?:" FMT_LETTER "|" FMT_DIGIT ")*")
#define FMT_HOSTADDR NCG(FMT_IP4ADDR "|" FMT_IP6ADDR)
#define FMT_IP4ADDR NCG(FMT_DIGIT "{1,3}\\." FMT_DIGIT "{1,3}\\." FMT_DIGIT "{1,3}\\." FMT_DIGIT "{1,3}")
#define FMT_IP6ADDR NCG(NCG(FMT_HEXDIGIT "{1,}(?::" FMT_HEXDIGIT "{1,})") "|" NCG("0:0:0:0:0:" NCG("0|FFFF") ":" FMT_IP4ADDR))
#define FMT_NICKNAME NCG(NCG(FMT_LETTER "|" FMT_SPECIAL) "(?:" FMT_LETTER "|" FMT_DIGIT "|" FMT_SPECIAL "|-){0,8}")
#define FMT_TARGETMASK NCG(NCG("$|#") FMT_MASK)
#define FMT_CHANSTRING NCG("(?:[\\x01-\\x07]|[\\x08-\\x09]|[\\x0B-\\x0C]|[\\x0E-\\x1F]|[\\x21-\\x2B]|[\\x2D-\\x39]|[\\x3B-\\xFF])*")
#define FMT_CHANNELID NCG("(?:[\\x41-5A]|" FMT_DIGIT "){5}")
#define FMT_USER NCG("(?:[\\x01-\\x09]|[\\x0B-\\x0C]|[\\x0E-\\x1F]|[\\x21-\\x3F]|[\\x41-\\xFF])+")
#define FMT_KEY NCG("(?:[\\x01-\\x05]|[\\x07-\\x08]|\\x0C|[\\x0E-\\x1F]|[\\x21-\\x7F]){1,23}")
#define FMT_LETTER NCG("[\\x41-\\x5A]|[\\x61-\\x7A]")
#define FMT_DIGIT NCG("[\\x30-\\x39]")
#define FMT_SPECIAL NCG("[\\x5B-\\x60]|[\\x7B-\\x7D]")
